server:
  port: 8002

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

spring:
  application:
    name: app-users
  devtools:
    restart:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/users?useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: main
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver